apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: kube-system
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: manifests/app/sealedsecrets
    repoURL: https://github.com/kainlite/tr
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
