apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: tr
spec:
  destination:
    namespace: tr
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: manifests/tekton/triggers
    repoURL: https://github.com/kainlite/tr
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
