# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "credo"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "dialyxir"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "excoveralls"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "ex_doc"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "esbuild"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "phoenix_live_reload"
        update-types: ["version-update:semver-patch"]
