version: '3'

services:
   db:
      image: postgres:14.5
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: tr_dev 
        PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432
   ollama:
      image: ollama/ollama:latest
      restart: always
      volumes:
        - ollama:/root/.ollama
      ports:
        - 11434:11434
      # requires nvidia-container-toolkit
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
volumes:
   pgdata:
   ollama:
