# Dockerignore for the test Dockerfile.
# More permissive than the production .dockerignore since we need /test/.

.dockerignore
Dockerfile.test.dockerignore

.git
!.git/HEAD
!.git/refs

/cover/
/doc/
/tmp/
.elixir_ls

/_build/
/deps/
*.ez

erl_crash.dump

/assets/node_modules/
/priv/static/assets/
/priv/static/cache_manifest.json
