apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: clone-build-push-run
  namespace: pipelines
spec:
  pipelineRef:
    name: clone-build-push
  taskRunTemplate: 
    podTemplate:
      securityContext:
        fsGroup: 65532
        # runAsNonRoot: true
        # runAsUser: 1001
        # seccompProfile:
        #   type: RuntimeDefault
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
  - name: kubeconfig-dir
    configMap:
      name: kubeconfig
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/kainlite/tr.git
  - name: image-reference
    value: kainlite/tr:latest
