apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: ollama
spec:
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/ollama
    repoURL: https://github.com/kainlite/tr
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
