apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
  serviceName: "ollama"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: ollama
    spec:
      imagePullSecrets:
      - name: regcred
      serviceAccountName: ollama
      containers:
        - name: ollama
          # securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #   readOnlyRootFilesystem: false
          #   runAsNonRoot: true
          #   runAsUser: 1000
          image: "ollama/ollama:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          args:
          resources:
            limits:
              cpu: 4000m
              memory: 8192Mi
            requests:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: [ "/bin/sh", "-c", "echo llama2 | xargs -n1 /bin/ollama pull " ]
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama
