apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: tr=ghcr.io/kainlite/tr:latest
    argocd-image-updater.argoproj.io/tr.update-strategy: digest
  name: tr
  namespace: tr
spec:
  destination:
    namespace: tr
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
      - ghcr.io/kainlite/tr:latest
    path: manifests
    repoURL: https://github.com/kainlite/tr
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
