apiVersion: apps/v1
kind: Deployment
metadata:
  name: tr-deployment
  namespace: tr
  labels:
    name: tr
    app: tr
spec:
  replicas: 3
  selector:
    matchLabels:
      name: tr
  template:
    metadata:
      labels:
        name: tr
        app: tr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: tr
        image: kainlite/tr:master
        envFrom:
        - secretRef:
            name: tr-postgres-config
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: RELEASE_COOKIE
          value: notreallyasecret
        # - name: RELEASE_DISTRIBUTION
        #   value: name
        # - name: RELEASE_NODE
        #   value: $(POD_NAME)@$(POD_IP)
        ports:
        - containerPort: 4000
        - containerPort: 4369
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
