apiVersion: apps/v1
kind: Deployment
metadata:
  name: tr-deployment
  namespace: tr
  labels:
    name: tr
    app: tr
spec:
  replicas: 3
  selector:
    matchLabels:
      name: tr
  template:
    metadata:
      labels:
        name: tr
        app: tr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      imagePullSecrets:
      - name: regcred
      containers:
      - name: tr
        image: kainlite/tr:master
        envFrom:
        - secretRef:
            name: tr-postgres-config
        - secretRef:
            name: tr-mailer-config
        - secretRef:
            name: tr-secret-key-config
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OLLAMA_ENDPOINT
          value: "http://ollama.ollama.svc.cluster.local:11434/api"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/app/bin/tr eval \"Tr.Release.migrate()\""]
        ports:
        - containerPort: 4000
        - containerPort: 4369
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
