apiVersion: v1
kind: Service
metadata:
  name: tr
  namespace: tr
spec:
  selector:
    name: tr
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: tr-cluster-svc
spec:
  clusterIP: None
  selector:
    app: tr-cluster-svc
  ports:
  - name: epmd
    port: 4369
