apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-k8s-conf
  labels:
    name: prometheus-k8s-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: 'monitoring-job'
      static_configs:
      - targets: ['opentelemetrycollector.monitoring.svc.cluster.local:9090']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
      batch:
        send_batch_size: 10000
        timeout: 5s
    exporters:
      prometheus:
        endpoint: ":9090"
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]
