kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  
  namespace: tr
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres  
  namespace: tr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: postgres
          image: postgres:14.5 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  
          envFrom:
            - secretRef:
                name: tr-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres 
  namespace: tr
  labels:
    app: postgres 
spec:
  type: ClusterIP 
  ports:
    - port: 5432 
  selector:
    app: postgres
