apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: livebook-data-pvc
  namespace: livebook
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
