---
name: 'build images'

on:
  push:

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v2

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: docker.io/kainlite/tr-gh:latest
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name docker.io/kainlite/tr-gh --digests --all-platforms /tmp/image.tar

      - name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.io/kainlite/tr-gh:latest
